name: github action tag

permissions:
  contents: write
  
on:
  pull_request:
    types:
      - closed

jobs:
  semver: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: git checkout local
      - uses: actions/checkout@v2

      - name: get latest tag from local git
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: plus minor version
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor

      - name: push tag to github origin main
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
