name: Java CI with Gradle

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # gradle 빌드 실행을 위한 권한을 부여
    - name: grant execute permission for gradlew
      run: chmod +x gradlew

    - name: gradle build
      run: ./gradlew clean build

    - name: build docker
      run: ./gradlew bootBuildImage --imageName=${{ secrets.DOCKERHUB_REPO }}

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: name/app
        
    - name: Docker push
      run:
        docker tag ${{ secrets.DOCKERHUB_REPO }}:${{ steps.meta.outputs.tags }} ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKERHUB_REPO}}:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKERHUB_REPO}}:latest
      
